import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
arr1=np.array([1,2,3,4,5])
print(arr1[1:4])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr[1,2])
print(arr[0,:])
print(arr[:,1])
print(arr[1:,1:])
print(arr+10)
print(arr*5)
b=np.array([10,20,30])
print(arr+b)
c=np.array([[1],[1]])
print(arr+c)
print(arr[1,2])